# 1) Hinge Loss 

## a) Hinge Loss on One Data Sample

In [1]:
import numpy as np

In [2]:
def hinge_loss_single(feature_vector, label, theta, theta_0):
    """
    Finds the hinge loss on a single data point given specific classification
    parameters.

    Args:
        feature_vector - A numpy array describing the given data point.
        label - A real valued number, the correct classification of the data
            point.
        theta - A numpy array describing the linear classifier.
        theta_0 - A real valued number representing the offset parameter.


    Returns: A real number representing the hinge loss associated with the
    given data point and parameters.
    """
    h = (np.dot(theta, feature_vector)) + theta_0
    z = np.dot(label, h)
    
    if z >= 1:
        hLoss = 0
    else:
        hLoss = 1 - z
    
    return hLoss

In [3]:
feature_vector = np.array([1, 2])
label, theta, theta_0 = 1, np.array([-1, 1]), -0.2

In [4]:
hinge_loss_single(feature_vector, label, theta, theta_0)

0.19999999999999996

## b) Hinge Loss on Data Set

In [5]:
def hinge_loss_full(feature_matrix, labels, theta, theta_0):
    """
    Finds the total hinge loss on a set of data given specific classification
    parameters.

    Args:
        feature_matrix - A numpy matrix describing the given data. Each row
            represents a single data point.
        labels - A numpy array where the kth element of the array is the
            correct classification of the kth row of the feature matrix.
        theta - A numpy array describing the linear classifier.
        theta_0 - A real valued number representing the offset parameter.


    Returns: A real number representing the hinge loss associated with the
    given dataset and parameters. This number should be the average hinge
    loss across all of the points in the feature matrix.
    """
    h_loss = 0
    for i in range(len(labels)): 
        h_loss = h_loss + hinge_loss_single(feature_matrix[i], labels[i], theta, theta_0)
    h_loss = h_loss / len(labels)
    return h_loss 

In [6]:
feature_vector = np.array([[1, 2], [1, 2]])
label, theta, theta_0 = np.array([1, 1]), np.array([-1, 1]), -0.2

In [7]:
hinge_loss_full(feature_vector, label, theta, theta_0)

0.19999999999999996

# 2) Perceptron Algorithm

## a) Perceptron Single Step Update 

In [8]:
def perceptron_single_step_update(
        feature_vector,
        label,
        current_theta,
        current_theta_0):
    """
    Properly updates the classification parameter, theta and theta_0, on a
    single step of the perceptron algorithm.

    Args:
        feature_vector - A numpy array describing a single data point.
        label - The correct classification of the feature vector.
        current_theta - The current theta being used by the perceptron
            algorithm before this update.
        current_theta_0 - The current theta_0 being used by the perceptron
            algorithm before this update.

    Returns: A tuple where the first element is a numpy array with the value of
    theta after the current update has completed and the second element is a
    real valued number with the value of theta_0 after the current updated has
    completed.
    """
    # first check
    ch = np.dot(label, np.dot(current_theta, feature_vector) + current_theta_0)
    
    if ch > 0:
        theta = current_theta
        theta_0 = current_theta_0
    else:
        theta = current_theta + (label * feature_vector)
        theta_0 = current_theta_0 + label
    
    new_par = (theta, theta_0)
    return new_par

In [9]:
feature_vector = np.array([1, 2])
label, theta, theta_0 = 1, np.array([-1, 1]), -1.5

In [10]:
per =perceptron_single_step_update(
        feature_vector,
        label,
        theta,
        theta_0)
per

(array([0, 3]), -0.5)

## b) Full Perceptron Algorithm 

In [11]:
import random 
def get_order(n_samples):
    try:
        with open(str(n_samples) + '.txt') as fp:
            line = fp.readline()
            return list(map(int, line.split(',')))
    except FileNotFoundError:
        random.seed(1)
        indicies = list(range(n_samples))
        random.shuffle(indicies)
        return indicies

In [12]:
get_order(10)

[6, 8, 9, 7, 5, 3, 0, 4, 1, 2]

In [13]:
def perceptron(feature_matrix, labels, T):
    """
    Runs the full perceptron algorithm on a given set of data. Runs T
    iterations through the data set, there is no need to worry about
    stopping early.

    NOTE: Please use the previously implemented functions when applicable.
    Do not copy paste code from previous parts.

    NOTE: Iterate the data matrix by the orders returned by get_order(feature_matrix.shape[0])

    Args:
        feature_matrix -  A numpy matrix describing the given data. Each row
            represents a single data point.
        labels - A numpy array where the kth element of the array is the
            correct classification of the kth row of the feature matrix.
        T - An integer indicating how many times the perceptron algorithm
            should iterate through the feature matrix.

    Returns: A tuple where the first element is a numpy array with the value of
    theta, the linear classification parameter, after T iterations through the
    feature matrix and the second element is a real number with the value of
    theta_0, the offset classification parameter, after T iterations through
    the feature matrix.
    """
    theta = np.zeros(feature_matrix.shape[1])
    theta_0 = 0
    for t in range(T):
        for i in get_order(feature_matrix.shape[0]):
            perc = perceptron_single_step_update(feature_matrix[i,:], 
                                                 labels[i],
                                                 theta, theta_0)
    return perc

In [14]:
feature_matrix = np.array([[1, 2]])
labels = np.array([1])
T = 1

In [15]:
f_perc = perceptron(feature_matrix, labels, T)
f_perc

(array([1., 2.]), 1)

## c) Average Perceptron Algorithm 

In [16]:
def average_perceptron(feature_matrix, labels, T):
    """
    Runs the average perceptron algorithm on a given set of data. Runs T
    iterations through the data set, there is no need to worry about
    stopping early.

    NOTE: Please use the previously implemented functions when applicable.
    Do not copy paste code from previous parts.

    NOTE: Iterate the data matrix by the orders returned by get_order(feature_matrix.shape[0])


    Args:
        feature_matrix -  A numpy matrix describing the given data. Each row
            represents a single data point.
        labels - A numpy array where the kth element of the array is the
            correct classification of the kth row of the feature matrix.
        T - An integer indicating how many times the perceptron algorithm
            should iterate through the feature matrix.

    Returns: A tuple where the first element is a numpy array with the value of
    the average theta, the linear classification parameter, found after T
    iterations through the feature matrix and the second element is a real
    number with the value of the average theta_0, the offset classification
    parameter, found after T iterations through the feature matrix.

    Hint: It is difficult to keep a running average; however, it is simple to
    find a sum and divide.
    """
    theta = np.zeros(feature_matrix.shape[1])
    theta_0 = 0.0
    
    # Keep track of the sum through the loops
    theta_sum = np.zeros(feature_matrix.shape[1])
    theta_0_sum = 0.0
    
    n = feature_matrix.shape[0]     # No of examples
    
    for t in range(T):
        for i in get_order(feature_matrix.shape[0]):
            theta, theta_0 = \
            perceptron_single_step_update(feature_matrix[i,:], labels[i], \
                                          theta, theta_0)
            
            theta_sum = theta_sum + theta
            theta_0_sum = theta_0_sum + theta_0
            
    theta_avg = (1/(n*T))*theta_sum
    theta_0_avg = (1/(n*T))*theta_0_sum
    
    return (theta_avg, theta_0_avg)

In [17]:
feature_matrix = np.array([[1, 2]])
labels = np.array([1])
T = 1

In [18]:
f_perc = average_perceptron(feature_matrix, labels, T)
f_perc

(array([1., 2.]), 1.0)

# 3) Pegasos Algorithm 

## a) Pegasos Single Step Update 

In [19]:
def pegasos_single_step_update(
        feature_vector,
        label,
        L,
        eta,
        current_theta,
        current_theta_0):
    """
    Properly updates the classification parameter, theta and theta_0, on a
    single step of the Pegasos algorithm

    Args:
        feature_vector - A numpy array describing a single data point.
        label - The correct classification of the feature vector.
        L - The lamba value being used to update the parameters.
        eta - Learning rate to update parameters.
        current_theta - The current theta being used by the Pegasos
            algorithm before this update.
        current_theta_0 - The current theta_0 being used by the
            Pegasos algorithm before this update.

    Returns: A tuple where the first element is a numpy array with the value of
    theta after the current update has completed and the second element is a
    real valued number with the value of theta_0 after the current updated has
    completed.
    """
    ch = float(label*(current_theta.dot(feature_vector) + current_theta_0))
    
    if ch <= 1.0:
        current_theta = (1-eta*L)*current_theta + eta*label*feature_vector
        current_theta_0 = current_theta_0 + eta*label
    else:
        current_theta = (1-eta*L)*current_theta
        
    return (current_theta, current_theta_0)

In [20]:
feature_vector = np.array([1, 2])
label, theta, theta_0 = 1, np.array([-1, 1]), -1.5
L = 0.2
eta = 0.1

In [21]:
pegasos_single_step_update(
        feature_vector,label,
        L,eta,theta,theta_0)

(array([-0.88,  1.18]), -1.4)

## b) Full Pegasos Algorithm 

In [22]:
def pegasos(feature_matrix, labels, T, L):
    """
    Runs the Pegasos algorithm on a given set of data. Runs T
    iterations through the data set, there is no need to worry about
    stopping early.

    For each update, set learning rate = 1/sqrt(t),
    where t is a counter for the number of updates performed so far (between 1
    and nT inclusive).

    NOTE: Please use the previously implemented functions when applicable.
    Do not copy paste code from previous parts.

    Args:
        feature_matrix - A numpy matrix describing the given data. Each row
            represents a single data point.
        labels - A numpy array where the kth element of the array is the
            correct classification of the kth row of the feature matrix.
        T - An integer indicating how many times the algorithm
            should iterate through the feature matrix.
        L - The lamba value being used to update the Pegasos
            algorithm parameters.

    Returns: A tuple where the first element is a numpy array with the value of
    the theta, the linear classification parameter, found after T
    iterations through the feature matrix and the second element is a real
    number with the value of the theta_0, the offset classification
    parameter, found after T iterations through the feature matrix.
    """
    # Counter
    c = 1
    
    # Initialize theta and theta0
    current_theta = np.zeros(feature_matrix.shape[1])
    current_theta_0 = 0.0
    
    for t in range(T):
        for i in get_order(feature_matrix.shape[0]):
            eta_t = 1/np.sqrt(c)  # Update eta every iteration
            c += 1 # Update counter
            
            # Run pegasos algorithm to get theta and theta0
            current_theta, current_theta_0 = pegasos_single_step_update(feature_matrix[i,:], \
             labels[i], L, eta_t, current_theta, current_theta_0)
            
    return (current_theta, current_theta_0)


In [23]:
feature_matrix = np.array([[1, 2]])
labels = np.array([1])
T = 1
L = 0.2

In [24]:
pegasos(feature_matrix, labels, T, L)

(array([1., 2.]), 1.0)

# Comparing Algorithms 

## Load Data 

In [47]:
import csv

In [44]:
def load_data(path_data, extras=False):
    """
    Returns a list of dict with keys:
    * sentiment: +1 or -1 if the review was positive or negative, respectively
    * text: the text of the review

    Additionally, if the `extras` argument is True, each dict will also include the
    following information:
    * productId: a string that uniquely identifies each product
    * userId: a string that uniquely identifies each user
    * summary: the title of the review
    * helpfulY: the number of users who thought this review was helpful
    * helpfulN: the number of users who thought this review was NOT helpful
    """


    basic_fields = {'sentiment', 'text'}
    numeric_fields = {'sentiment', 'helpfulY', 'helpfulN'}

    data = []

    f_data = open(path_data, encoding="latin1")

    for datum in csv.DictReader(f_data, delimiter='\t'):
        for field in list(datum.keys()):
            if not extras and field not in basic_fields:
                del datum[field]
            elif field in numeric_fields and datum[field]:
                datum[field] = int(datum[field])

        data.append(datum)

    f_data.close()

In [53]:
train_data = load_data("sentiment_analysis\reviews_train.tsv")
val_data = load_data('sentiment_analysis/reviews_val.tsv')
test_data = load_data('sentiment_analysis/reviews_test.tsv')

train_texts, train_labels = zip(*((sample['text'], sample['sentiment']) for sample in train_data))
val_texts, val_labels = zip(*((sample['text'], sample['sentiment']) for sample in val_data))
test_texts, test_labels = zip(*((sample['text'], sample['sentiment']) for sample in test_data))

dictionary = p1.bag_of_words(train_texts)

train_bow_features = p1.extract_bow_feature_vectors(train_texts, dictionary)
val_bow_features = p1.extract_bow_feature_vectors(val_texts, dictionary)
test_bow_features = p1.extract_bow_feature_vectors(test_texts, dictionary)

OSError: [Errno 22] Invalid argument: 'sentiment_analysis\reviews_train.tsv'

In [51]:
train_data